FROM golang:alpine as server

ENV GO111MODULE=on
ENV GOPROXY=https://goproxy.io,direct
WORKDIR /go/src/gf-vue-admin
COPY server/ ./

RUN cat ./config/config.toml
COPY .docker-compose/shell/server-handle.sh .
RUN sh ./server-handle.sh
RUN rm -f server-handle.sh
RUN cat ./config/config.toml

RUN go env && go list && go build -o server .

FROM alpine:latest
MAINTAINER SliverHorn <sliver_horn@qq.com>

WORKDIR gf-vue-admin/

# copy server
COPY --from=server /go/src/gf-vue-admin/server ./
COPY --from=server /go/src/gf-vue-admin/i18n ./i18n
COPY --from=server /go/src/gf-vue-admin/local ./local
COPY --from=server /go/src/gf-vue-admin/public ./public
COPY --from=server /go/src/gf-vue-admin/config ./config
COPY --from=server /go/src/gf-vue-admin/template ./template

EXPOSE 8888

ENTRYPOINT ./server