// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package apis

import "github.com/gogf/gf/os/gtime"

type Apis struct {
	Id          uint        `orm:"id,primary"  json:"ID"`          // 自增ID
	CreateAt    *gtime.Time `orm:"create_at"   json:"CreatedAt"`   // 创建时间
	UpdateAt    *gtime.Time `orm:"update_at"   json:"UpdatedAt"`   // 更新时间
	DeleteAt    *gtime.Time `orm:"delete_at"   json:"DeletedAt"`   // 删除时间
	Path        string      `orm:"path"        json:"path"`        // api路径
	Description string      `orm:"description" json:"description"` // api中文描述
	ApiGroup    string      `orm:"api_group"   json:"apiGroup"`    // api组
	Method      string      `orm:"method"      json:"method"`      // 方法
}

// RecordNotFound 根据条件判断数据是否存在
// 有数据返回false
// 没数据 true
func RecordNotFound(where ...interface{}) bool {
	return Model.RecordNotFound(where...)
}

func (m *arModel) RecordNotFound(where ...interface{}) bool {
	r, err := m.M.FindOne(where...)
	if r == nil && err == nil {
		return true
	}
	return false
}
