// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// adminDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type adminDao struct {
	*internal.AdminDao
}

var (
	// Admin is globally public accessible object for table admin operations.
	Admin = &adminDao{
		internal.Admin,
	}
)

// Fill with you ideas below.