// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// authorityMenuDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type authorityMenuDao struct {
	*internal.AuthorityMenuDao
}

var (
	// AuthorityMenu is globally public accessible object for table authority_menu operations.
	AuthorityMenu = &authorityMenuDao{
		internal.AuthorityMenu,
	}
)

// Fill with you ideas below.