// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// baseMenusDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type baseMenusDao struct {
	*internal.BaseMenusDao
}

var (
	// BaseMenus is globally public accessible object for table base_menus operations.
	BaseMenus = &baseMenusDao{
		internal.BaseMenus,
	}
)

// Fill with you ideas below.