// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// coffeeDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type coffeeDao struct {
	*internal.CoffeeDao
}

var (
	// Coffee is globally public accessible object for table coffee operations.
	Coffee = &coffeeDao{
		internal.Coffee,
	}
)

// Fill with you ideas below.