// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// dictionariesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type dictionariesDao struct {
	*internal.DictionariesDao
}

var (
	// Dictionaries is globally public accessible object for table dictionaries operations.
	Dictionaries = &dictionariesDao{
		internal.Dictionaries,
	}
)

// Fill with you ideas below.