// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// filesDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type filesDao struct {
	*internal.FilesDao
}

var (
	// Files is globally public accessible object for table files operations.
	Files = &filesDao{
		internal.Files,
	}
)

// Fill with you ideas below.