// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// jwtBlacklistDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type jwtBlacklistDao struct {
	*internal.JwtBlacklistDao
}

var (
	// JwtBlacklist is globally public accessible object for table jwt_blacklist operations.
	JwtBlacklist = &jwtBlacklistDao{
		internal.JwtBlacklist,
	}
)

// Fill with you ideas below.