// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// menusParametersDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type menusParametersDao struct {
	*internal.MenusParametersDao
}

var (
	// MenusParameters is globally public accessible object for table menus_parameters operations.
	MenusParameters = &menusParametersDao{
		internal.MenusParameters,
	}
)

// Fill with you ideas below.