// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package dao

import (
	"server/app/dao/internal"
)

// operationRecordsDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type operationRecordsDao struct {
	*internal.OperationRecordsDao
}

var (
	// OperationRecords is globally public accessible object for table operation_records operations.
	OperationRecords = &operationRecordsDao{
		internal.OperationRecords,
	}
)

// Fill with you ideas below.