// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================
package simple_upload

// RecordNotFound 根据条件判断数据是否存在
// 有数据返回false
// 没数据 true
func RecordNotFound(where ...interface{}) bool {
	return Model.RecordNotFound(where...)
}

func (m *arModel) RecordNotFound(where ...interface{}) bool {
	r, err := m.M.FindOne(where...)
	if r == nil && err == nil {
		return true
	}
	return false
}

// Custom Model
type SimpleUpload struct {
	ChunkNumber      string `json:"chunkNumber"`      // 当前切片标记
	CurrentChunkPath string `json:"currentChunkPath"` // 切片本地路径
	CurrentChunkSize string `json:"currentChunkSize"` // 当前切片容量
	FilePath         string `json:"filePath"`         // 文件本地路径
	Filename         string `json:"filename"`         // 文件名
	Identifier       string `json:"identifier"`       // 文件标识（md5）
	IsDone           int    `json:"isDone"`           // 是否上传完成
	TotalChunks      string `json:"totalChunks"`      // 切片总数
	TotalSize        string `json:"totalSize"`        // 总容量
}
