// ============================================================================
// This is auto-generated by gf cli tool only once. Fill this file as you wish.
// ============================================================================

package breakpoint_files

import "github.com/gogf/gf/os/gtime"

type ExaFile struct {
	Id         uint        `orm:"id,primary"  json:"id"`          // 自增ID
	CreateAt   *gtime.Time `orm:"create_at"   json:"create_at"`   // 更新时间
	UpdateAt   *gtime.Time `orm:"update_at"   json:"update_at"`   // 更新时间
	DeleteAt   *gtime.Time `orm:"delete_at"   json:"delete_at"`   // 删除时间
	FileName   string      `orm:"file_name"   json:"file_name"`   // 文件名
	FileMd5    string      `orm:"file_md5"    json:"file_md_5"`   // 文件md5
	FilePath   string      `orm:"file_path"   json:"file_path"`   // 文件路径
	ChunkId    int         `orm:"chunk_id"    json:"chunk_id"`    // 关联id
	ChunkTotal int         `orm:"chunk_total" json:"chunk_total"` // 切片总数
	IsFinish   int         `orm:"is_finish"   json:"is_finish"`   // 是否完整
}

// RecordNotFound 根据条件判断数据是否存在
// 有数据返回false
// 没数据 true
func RecordNotFound(where ...interface{}) bool {
	return Model.RecordNotFound(where...)
}

func (m *arModel) RecordNotFound(where ...interface{}) bool {
	r, err := m.M.FindOne(where...)
	if r == nil && err == nil {
		return true
	}
	return false
}
